import tfdaFoods from "./tfda-foods.json";

export type FoodDataSource =
  | "tfda"
  | "nutrition-label"
  | "open-food-facts"
  | "estimate"
  | "user"
  | "ai";

export type Food = {
  id: string;
  name: string;
  source: string;
  category: string;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  sodium?: number;
  sugar?: number;
  fiber?: number;
  aliases?: string[];
  servingGrams?: number;
  servingLabel?: string;
  barcode?: string;
  dataSource?: FoodDataSource;
  sourceName?: string;
  sourceUrl?: string;
  confidence?: "official" | "label" | "community" | "estimated";
};

type Kind = "meal" | "drink" | "snack";
type BaseFood = Food & { kind: Kind };

const group = (
  source: string,
  category: string,
  kind: Kind,
  names: string[],
  kcal: number,
  protein: number,
  carbs: number,
  fat: number,
): BaseFood[] =>
  names.map((name, index) => ({
    id: `${source}-${category}-${index}`,
    name,
    source,
    category,
    kind,
    kcal: Math.max(30, Math.round(kcal + ((index % 5) - 2) * 18)),
    protein: Math.max(0, Math.round(protein + ((index % 4) - 1) * 2)),
    carbs: Math.max(0, Math.round(carbs + ((index % 5) - 2) * 3)),
    fat: Math.max(0, Math.round(fat + ((index % 3) - 1) * 2)),
  }));

const bases: BaseFood[] = [
  ...group(
    "便利商店",
    "早餐",
    "meal",
    [
      "茶葉蛋＋地瓜",
      "鮪魚飯糰＋茶葉蛋",
      "鮭魚飯糰＋無糖豆漿",
      "雞肉飯糰＋優格",
      "全麥三明治＋鮮奶",
      "火腿蛋三明治＋黑咖啡",
      "烤地瓜＋無糖優格",
      "燕麥杯＋香蕉",
      "御飯糰＋低脂鮮奶",
      "溏心蛋＋烤地瓜",
      "蔬菜蛋三明治",
      "鮪魚蛋三明治",
      "雞胸肉三明治",
      "起司蛋貝果",
      "玉米蛋沙拉吐司",
    ],
    340,
    19,
    47,
    9,
  ),
  ...group(
    "便利商店",
    "高蛋白",
    "meal",
    [
      "舒肥雞胸便當",
      "雞胸肉＋茶葉蛋",
      "雞肉沙拉＋無糖豆漿",
      "鮪魚沙拉＋水煮蛋",
      "烤雞蔬菜餐盒",
      "鹽水雞胸＋地瓜",
      "毛豆＋雞胸肉",
      "雞胸肉＋御飯糰",
      "高蛋白餐盒",
      "滷牛腱餐盒",
      "鮭魚健康餐盒",
      "雞肉藜麥沙拉",
      "豆腐雞肉沙拉",
      "蛋白丁＋雞胸肉",
      "低脂雞肉義大利麵",
    ],
    430,
    34,
    42,
    12,
  ),
  ...group(
    "台式早餐店",
    "早餐",
    "meal",
    [
      "蛋餅",
      "起司蛋餅",
      "鮪魚蛋餅",
      "玉米蛋餅",
      "蔬菜蛋餅",
      "火腿蛋吐司",
      "鮪魚蛋吐司",
      "豬排蛋吐司",
      "雞肉蛋漢堡",
      "里肌蛋漢堡",
      "蘿蔔糕加蛋",
      "飯糰加蛋",
      "鐵板麵加蛋",
      "全麥蛋餅",
      "薯餅蛋塔",
    ],
    430,
    18,
    51,
    18,
  ),
  ...group(
    "便當店",
    "便當",
    "meal",
    [
      "烤雞胸便當",
      "滷雞腿便當",
      "炸雞腿便當",
      "滷排骨便當",
      "炸排骨便當",
      "滷牛腱便當",
      "烤鯖魚便當",
      "烤鮭魚便當",
      "虱目魚便當",
      "三杯雞便當",
      "宮保雞丁便當",
      "蔥爆牛肉便當",
      "黑胡椒豬柳便當",
      "糖醋里肌便當",
      "控肉便當",
      "滷肉便當",
      "豆腐蔬食便當",
      "鹽水雞便當",
      "蒜泥白肉便當",
      "打拋豬便當",
    ],
    690,
    34,
    76,
    27,
  ),
  ...group(
    "麵食",
    "正餐",
    "meal",
    [
      "紅燒牛肉麵",
      "清燉牛肉麵",
      "榨菜肉絲麵",
      "麻醬麵",
      "乾麵加滷蛋",
      "餛飩麵",
      "陽春麵",
      "鍋燒意麵",
      "鍋燒烏龍麵",
      "雞絲麵",
      "肉燥米粉",
      "海鮮湯麵",
      "牛肉湯麵",
      "擔仔麵",
      "炸醬麵",
      "酸辣麵",
      "麻辣牛肉麵",
      "番茄牛肉麵",
    ],
    620,
    26,
    82,
    20,
  ),
  ...group(
    "台式小吃",
    "正餐",
    "meal",
    [
      "雞肉飯",
      "滷肉飯",
      "火雞肉飯",
      "肉羹飯",
      "蚵仔麵線",
      "大腸麵線",
      "水餃 10 顆",
      "鍋貼 10 顆",
      "肉圓",
      "碗粿",
      "米糕",
      "油飯",
      "刈包",
      "鹹粥",
      "皮蛋瘦肉粥",
      "廣東粥",
      "肉羹麵",
      "魯肉乾麵",
      "鴨肉飯",
      "排骨酥麵",
    ],
    560,
    23,
    70,
    21,
  ),
  ...group(
    "速食",
    "速食",
    "meal",
    [
      "辣雞腿堡",
      "雙層牛肉堡",
      "牛肉起司堡",
      "烤雞堡",
      "魚排堡",
      "炸雞兩塊",
      "雞塊六塊",
      "豬肉滿福堡加蛋",
      "雞肉捲",
      "烤雞沙拉",
      "凱薩雞肉沙拉",
      "薯條＋雞塊",
      "牛肉堡＋玉米濃湯",
      "雞腿堡＋沙拉",
      "炸雞＋無糖茶",
      "潛艇堡烤雞 6 吋",
      "潛艇堡牛肉 6 吋",
      "墨西哥雞肉捲",
    ],
    570,
    27,
    55,
    27,
  ),
  ...group(
    "日式",
    "正餐",
    "meal",
    [
      "鮭魚生魚片丼",
      "鮪魚生魚片丼",
      "握壽司 8 貫",
      "親子丼",
      "牛丼",
      "豬排丼",
      "天丼",
      "日式咖哩雞飯",
      "日式咖哩豬排飯",
      "烤鯖魚定食",
      "烤鮭魚定食",
      "薑燒豬肉定食",
      "唐揚雞定食",
      "蕎麥麵",
      "烏龍麵",
      "豚骨拉麵",
      "醬油拉麵",
      "味噌拉麵",
    ],
    690,
    31,
    85,
    25,
  ),
  ...group(
    "韓式",
    "正餐",
    "meal",
    [
      "韓式石鍋拌飯",
      "泡菜豆腐鍋",
      "海鮮豆腐鍋",
      "韓式烤肉飯",
      "韓式炸雞飯",
      "部隊鍋",
      "韓式冷麵",
      "韓式拌麵",
      "辣炒年糕",
      "泡菜炒飯",
      "韓式牛肉湯飯",
      "蔘雞湯",
      "韓式紫菜飯捲",
      "春川辣炒雞",
      "韓式烤五花肉",
    ],
    710,
    30,
    82,
    29,
  ),
  ...group(
    "東南亞",
    "正餐",
    "meal",
    [
      "越南牛肉河粉",
      "越南雞肉河粉",
      "海南雞飯",
      "打拋豬飯",
      "打拋雞飯",
      "綠咖哩雞飯",
      "紅咖哩牛肉飯",
      "月亮蝦餅套餐",
      "椒麻雞飯",
      "泰式炒河粉",
      "叻沙麵",
      "肉骨茶飯",
      "印尼炒飯",
      "越南春捲套餐",
      "泰式檸檬魚飯",
    ],
    670,
    31,
    81,
    24,
  ),
  ...group(
    "火鍋",
    "高蛋白",
    "meal",
    [
      "牛肉小火鍋",
      "豬肉小火鍋",
      "雞肉小火鍋",
      "海鮮小火鍋",
      "豆腐蔬食鍋",
      "麻辣牛肉鍋",
      "泡菜豬肉鍋",
      "昆布海鮮鍋",
      "壽喜燒牛肉鍋",
      "酸菜白肉鍋",
      "藥膳羊肉鍋",
      "番茄雞肉鍋",
      "牛奶海鮮鍋",
      "石頭牛肉鍋",
      "剝皮辣椒雞鍋",
    ],
    700,
    39,
    53,
    34,
  ),
  ...group(
    "健康餐",
    "高蛋白",
    "meal",
    [
      "舒肥雞胸健康餐",
      "香煎雞腿健康餐",
      "嫩煎牛肉健康餐",
      "烤鮭魚健康餐",
      "烤鯖魚健康餐",
      "蝦仁健康餐",
      "豆腐蔬食健康餐",
      "雞胸藜麥餐盒",
      "牛肉糙米餐盒",
      "鮭魚地瓜餐盒",
      "雞肉花椰菜米餐盒",
      "低脂豬里肌餐盒",
      "毛豆豆腐餐盒",
      "鮪魚蛋沙拉",
      "雞胸酪梨沙拉",
      "牛肉生菜沙拉",
      "鮭魚生菜沙拉",
      "夏威夷鮭魚拌飯",
    ],
    510,
    39,
    48,
    17,
  ),
  ...group(
    "素食",
    "正餐",
    "meal",
    [
      "蔬食便當",
      "豆腐蔬菜便當",
      "素滷味拼盤",
      "蔬菜咖哩飯",
      "菇菇燉飯",
      "番茄蔬菜義大利麵",
      "青醬菇菇義大利麵",
      "豆皮烏龍麵",
      "蔬食水餃 10 顆",
      "素肉燥飯",
      "蔬菜豆腐鍋",
      "藜麥毛豆沙拉",
      "鷹嘴豆沙拉",
      "素雞排便當",
      "麻婆豆腐飯",
    ],
    540,
    20,
    75,
    18,
  ),
  ...group(
    "西式餐廳",
    "正餐",
    "meal",
    [
      "8oz 牛排＋蔬菜",
      "烤雞腿排＋蔬菜",
      "香煎鮭魚＋蔬菜",
      "奶油培根義大利麵",
      "番茄海鮮義大利麵",
      "青醬雞肉義大利麵",
      "白醬雞肉燉飯",
      "番茄牛肉燉飯",
      "總匯三明治",
      "雞肉帕尼尼",
      "鮪魚貝果",
      "燻鮭魚貝果",
      "烤雞凱薩沙拉",
      "牛肉捲餅",
      "雞肉墨西哥碗",
    ],
    680,
    35,
    68,
    29,
  ),
  ...group(
    "夜市",
    "正餐",
    "meal",
    [
      "大雞排",
      "鹽酥雞一份",
      "滷味綜合拼盤",
      "臭豆腐",
      "蚵仔煎",
      "花枝羹",
      "地瓜球",
      "蔥油餅加蛋",
      "胡椒餅",
      "烤香腸",
      "烤玉米",
      "章魚燒",
      "大腸包小腸",
      "雞肉串兩串",
      "牛肉串兩串",
      "甘梅地瓜",
      "炸魷魚",
      "藥燉排骨",
    ],
    540,
    21,
    52,
    28,
  ),
  ...group(
    "飲品店",
    "飲品",
    "drink",
    [
      "無糖紅茶",
      "無糖綠茶",
      "無糖烏龍茶",
      "微糖紅茶",
      "微糖綠茶",
      "珍珠奶茶",
      "波霸鮮奶茶",
      "紅茶拿鐵",
      "烏龍拿鐵",
      "冬瓜茶",
      "百香綠茶",
      "檸檬紅茶",
      "多多綠茶",
      "水果茶",
      "芋頭鮮奶",
      "黑糖珍珠鮮奶",
      "仙草奶茶",
      "椰果綠茶",
    ],
    260,
    5,
    47,
    6,
  ),
  ...group(
    "咖啡店",
    "飲品",
    "drink",
    [
      "冰美式",
      "熱美式",
      "無糖拿鐵",
      "燕麥奶拿鐵",
      "豆奶拿鐵",
      "卡布奇諾",
      "摩卡咖啡",
      "焦糖瑪奇朵",
      "抹茶拿鐵",
      "伯爵鮮奶茶",
      "可可鮮奶",
      "冷萃咖啡",
      "馥芮白",
      "西西里咖啡",
      "蜂蜜拿鐵",
    ],
    170,
    7,
    20,
    7,
  ),
  ...group(
    "甜點店",
    "甜點",
    "snack",
    [
      "原味蛋糕",
      "起司蛋糕",
      "巧克力蛋糕",
      "提拉米蘇",
      "蛋塔",
      "泡芙",
      "可頌",
      "肉桂捲",
      "紅豆麵包",
      "菠蘿麵包",
      "奶酥吐司",
      "鬆餅",
      "雞蛋糕 6 顆",
      "車輪餅",
      "豆花",
      "仙草凍",
      "紅豆湯",
      "芋圓甜湯",
    ],
    340,
    7,
    48,
    14,
  ),
  ...group(
    "運動補給",
    "運動後",
    "snack",
    [
      "乳清蛋白一份",
      "低脂鮮奶 300ml",
      "無糖豆漿 400ml",
      "香蕉＋無糖豆漿",
      "希臘優格＋莓果",
      "雞胸肉＋香蕉",
      "茶葉蛋 2 顆＋牛奶",
      "巧克力牛奶",
      "高蛋白優格",
      "蛋白棒",
      "鮪魚三明治",
      "地瓜＋乳清蛋白",
    ],
    260,
    23,
    31,
    6,
  ),
];

const mealVariants = [
  { id: "standard", label: "", scale: 1, add: [0, 0, 0, 0] },
  { id: "small", label: "（小份）", scale: 0.78, add: [0, 0, 0, 0] },
  { id: "large", label: "（大份）", scale: 1.25, add: [0, 0, 0, 0] },
  { id: "half", label: "（主食半份）", scale: 0.84, add: [0, 0, -18, 0] },
  { id: "egg", label: "＋蛋", scale: 1, add: [75, 7, 1, 5] },
  { id: "veg", label: "＋青菜", scale: 1, add: [45, 3, 8, 1] },
];
const drinkVariants = [
  { id: "small", label: "（小杯）", scale: 0.75, add: [0, 0, 0, 0] },
  { id: "medium", label: "（中杯）", scale: 1, add: [0, 0, 0, 0] },
  { id: "large", label: "（大杯）", scale: 1.28, add: [0, 0, 0, 0] },
  { id: "sugarfree", label: "（無糖）", scale: 0.42, add: [0, 0, -20, 0] },
  { id: "half-sugar", label: "（半糖）", scale: 0.72, add: [0, 0, -11, 0] },
  { id: "less-ice", label: "（少冰）", scale: 1.06, add: [0, 0, 3, 0] },
];
const snackVariants = [
  { id: "half", label: "（半份）", scale: 0.5, add: [0, 0, 0, 0] },
  { id: "standard", label: "", scale: 1, add: [0, 0, 0, 0] },
  { id: "large", label: "（大份）", scale: 1.35, add: [0, 0, 0, 0] },
  { id: "share", label: "（分享份）", scale: 1.7, add: [0, 0, 0, 0] },
  { id: "protein", label: "＋高蛋白飲", scale: 1, add: [130, 24, 5, 2] },
  { id: "fruit", label: "＋水果", scale: 1, add: [90, 1, 23, 0] },
];

const singleGroup = (
  source: string,
  category: string,
  names: string[],
  kcal: number,
  protein: number,
  carbs: number,
  fat: number,
  sodium: number,
  sugar: number,
  fiber: number,
): Food[] =>
  names.map((name, index) => ({
    id: `single-${source}-${category}-${index}`,
    name,
    source,
    category,
    kcal: Math.max(5, Math.round(kcal + ((index % 5) - 2) * 12)),
    protein: Math.max(0, Math.round(protein + ((index % 4) - 1) * 1.5)),
    carbs: Math.max(0, Math.round(carbs + ((index % 5) - 2) * 2)),
    fat: Math.max(0, Math.round(fat + ((index % 3) - 1))),
    sodium: Math.max(0, Math.round(sodium + ((index % 5) - 2) * 25)),
    sugar: Math.max(0, Math.round(sugar + ((index % 4) - 1))),
    fiber: Math.max(0, Math.round((fiber + ((index % 3) - 1) * 0.5) * 10) / 10),
  }));

/** 單品優先資料庫：每一項都能獨立記錄，不強迫使用固定組合。 */
export const SINGLE_FOODS: Food[] = [
  ...singleGroup(
    "便利商店",
    "蛋白質",
    [
      "茶葉蛋 1 顆",
      "溏心蛋 1 顆",
      "水煮蛋 1 顆",
      "滷蛋 1 顆",
      "荷包蛋 1 顆",
      "雞胸肉 1 份",
      "舒肥雞胸 1 份",
      "鮪魚罐頭 1 份",
      "毛豆 1 盒",
      "板豆腐半盒",
      "嫩豆腐半盒",
      "無糖希臘優格 1 杯",
    ],
    105,
    12,
    3,
    5,
    310,
    1,
    1,
  ),
  ...singleGroup(
    "便利商店",
    "主食",
    [
      "烤地瓜 100g",
      "御飯糰 1 顆",
      "鮭魚飯糰 1 顆",
      "鮪魚飯糰 1 顆",
      "雞肉飯糰 1 顆",
      "白飯半碗",
      "糙米飯半碗",
      "玉米 1 根",
      "燕麥杯 1 份",
      "全麥吐司 1 片",
      "原味貝果 1 個",
      "馬鈴薯 100g",
    ],
    180,
    5,
    37,
    2,
    190,
    3,
    3,
  ),
  ...singleGroup(
    "便利商店",
    "飲品",
    [
      "無糖豆漿 400ml",
      "低脂鮮奶 300ml",
      "高蛋白牛奶 1 瓶",
      "無糖優酪乳 1 瓶",
      "黑咖啡 1 杯",
      "冰美式 1 杯",
      "無糖綠茶 1 瓶",
      "無糖烏龍茶 1 瓶",
      "氣泡水 1 瓶",
      "椰子水 1 瓶",
      "拿鐵 1 杯",
      "燕麥奶 300ml",
    ],
    115,
    7,
    14,
    4,
    85,
    7,
    1,
  ),
  ...singleGroup(
    "早餐店",
    "早餐",
    [
      "原味蛋餅 1 份",
      "起司蛋餅 1 份",
      "火腿蛋吐司 1 份",
      "鮪魚蛋吐司 1 份",
      "里肌蛋吐司 1 份",
      "蘿蔔糕 2 片",
      "薯餅 1 片",
      "蔥抓餅 1 份",
      "小籠包 5 顆",
      "燒餅 1 個",
      "油條 1 根",
      "飯糰 1 顆",
    ],
    330,
    13,
    40,
    13,
    650,
    4,
    2,
  ),
  ...singleGroup(
    "自助餐",
    "蛋白質",
    [
      "滷雞腿 1 支",
      "烤雞腿 1 支",
      "炸雞腿 1 支",
      "滷排骨 1 片",
      "炸排骨 1 片",
      "煎鯖魚半片",
      "烤鮭魚 1 片",
      "滷牛腱 100g",
      "蒜泥白肉 100g",
      "三杯雞 1 份",
      "宮保雞丁 1 份",
      "蒸魚 1 份",
    ],
    285,
    25,
    8,
    17,
    680,
    3,
    1,
  ),
  ...singleGroup(
    "自助餐",
    "蔬菜",
    [
      "燙青菜 1 份",
      "高麗菜 1 份",
      "花椰菜 1 份",
      "菠菜 1 份",
      "空心菜 1 份",
      "地瓜葉 1 份",
      "炒菇 1 份",
      "番茄炒蛋 1 份",
      "苦瓜炒蛋 1 份",
      "炒豆芽 1 份",
      "海帶 1 份",
      "筍絲 1 份",
    ],
    85,
    4,
    10,
    4,
    260,
    3,
    4,
  ),
  ...singleGroup(
    "台式小吃",
    "小吃",
    [
      "水餃 1 顆",
      "鍋貼 1 顆",
      "小籠包 1 顆",
      "肉圓 1 顆",
      "碗粿 1 個",
      "刈包 1 個",
      "滷味豆干 1 塊",
      "滷味米血 1 塊",
      "滷味百頁豆腐 1 份",
      "甜不辣 1 片",
      "貢丸 1 顆",
      "黑輪 1 條",
    ],
    125,
    6,
    14,
    5,
    360,
    2,
    1,
  ),
  ...singleGroup(
    "速食",
    "單點",
    [
      "牛肉漢堡 1 個",
      "辣雞腿堡 1 個",
      "烤雞堡 1 個",
      "魚排堡 1 個",
      "炸雞 1 塊",
      "雞塊 1 塊",
      "小薯 1 份",
      "玉米濃湯 1 杯",
      "生菜沙拉 1 份",
      "玉米杯 1 份",
      "蘋果片 1 份",
      "雞肉捲 1 份",
    ],
    265,
    13,
    28,
    11,
    520,
    5,
    2,
  ),
  ...singleGroup(
    "水果",
    "水果",
    [
      "香蕉 1 根",
      "蘋果 1 顆",
      "芭樂半顆",
      "奇異果 1 顆",
      "橘子 1 顆",
      "葡萄 10 顆",
      "鳳梨 1 碗",
      "木瓜 1 碗",
      "西瓜 1 碗",
      "藍莓 1 碗",
      "草莓 6 顆",
      "小番茄 10 顆",
    ],
    85,
    1,
    20,
    0,
    5,
    14,
    3,
  ),
  ...singleGroup(
    "點心",
    "點心",
    [
      "原味堅果 1 小包",
      "蛋白棒 1 根",
      "蘇打餅乾 3 片",
      "洋芋片 1 小包",
      "黑巧克力 2 小片",
      "雞蛋糕 1 顆",
      "車輪餅 1 個",
      "蛋塔 1 個",
      "泡芙 1 個",
      "起司蛋糕 1 片",
      "豆花 1 碗",
      "仙草凍 1 碗",
    ],
    185,
    5,
    23,
    9,
    180,
    12,
    2,
  ),
  ...singleGroup(
    "飲料店",
    "飲品",
    [
      "無糖紅茶 1 杯",
      "無糖綠茶 1 杯",
      "無糖烏龍茶 1 杯",
      "微糖紅茶 1 杯",
      "微糖綠茶 1 杯",
      "珍珠奶茶 1 杯",
      "鮮奶茶 1 杯",
      "冬瓜茶 1 杯",
      "水果茶 1 杯",
      "多多綠茶 1 杯",
      "黑糖珍珠鮮奶 1 杯",
      "檸檬水 1 杯",
    ],
    190,
    3,
    37,
    4,
    70,
    28,
    0,
  ),
  ...singleGroup(
    "運動補給",
    "運動後",
    [
      "乳清蛋白 1 份",
      "植物蛋白 1 份",
      "高蛋白優格 1 杯",
      "香蕉牛奶 1 杯",
      "巧克力牛奶 1 瓶",
      "低脂巧克力奶 1 瓶",
      "鮪魚 100g",
      "雞胸肉 100g",
      "豆漿 300ml",
      "鮮奶 300ml",
      "香蕉 1 根",
      "烤地瓜 100g",
    ],
    150,
    18,
    16,
    3,
    150,
    7,
    1,
  ),
];

export const FOOD_LIBRARY: Food[] = bases.flatMap((base) => {
  const variants =
    base.kind === "drink"
      ? drinkVariants
      : base.kind === "snack"
        ? snackVariants
        : mealVariants;
  return variants.map((v) => ({
    id: `${base.id}-${v.id}`,
    name: `${base.name}${v.label}`,
    source: base.source,
    category: base.category,
    kcal: Math.max(0, Math.round(base.kcal * v.scale + v.add[0])),
    protein: Math.max(0, Math.round(base.protein * v.scale + v.add[1])),
    carbs: Math.max(0, Math.round(base.carbs * v.scale + v.add[2])),
    fat: Math.max(0, Math.round(base.fat * v.scale + v.add[3])),
    sodium: Math.round(
      (base.kind === "drink"
        ? 90
        : base.category === "甜點"
          ? 220
          : base.source === "便利商店"
            ? 620
            : 850) * v.scale,
    ),
    sugar: Math.max(
      0,
      Math.round(
        (base.kind === "drink" ? 26 : base.category === "甜點" ? 24 : 5) *
          v.scale,
      ),
    ),
    fiber: Math.max(
      0,
      Math.round(
        (base.category === "高蛋白" ? 5 : base.kind === "meal" ? 4 : 1) *
          v.scale *
          10,
      ) / 10,
    ),
  }));
});

/**
 * 衛福部食藥署食品營養成分資料集的精簡匯入版本。
 * 數值依官方每單位含量；沒有單位重量時，以 100g 為預設份量。
 */
type CompactTfdaFood = [
  string,
  string,
  string,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  string[],
  number,
  string,
];

export const TFDA_FOODS: Food[] = (tfdaFoods as CompactTfdaFood[]).map(
  ([
    id,
    name,
    category,
    kcal,
    protein,
    carbs,
    fat,
    sodium,
    sugar,
    fiber,
    aliases,
    servingGrams,
    servingLabel,
  ]) => ({
    id,
    name,
    source: "食藥署",
    category,
    kcal,
    protein,
    carbs,
    fat,
    sodium,
    sugar,
    fiber,
    aliases,
    servingGrams,
    servingLabel,
    dataSource: "tfda",
    sourceName: "衛生福利部食品藥物管理署",
    sourceUrl: "https://data.gov.tw/dataset/8543",
    confidence: "official",
  }),
);

export const EXERCISES = [
  { name: "散步", met: 3.0 },
  { name: "快走", met: 4.3 },
  { name: "爬樓梯", met: 8.8 },
  { name: "健走登山", met: 6.0 },
  { name: "慢跑", met: 8.0 },
  { name: "跑步（中等速度）", met: 9.8 },
  { name: "跑步（快速）", met: 11.5 },
  { name: "跑步機快走", met: 4.8 },
  { name: "蛙式游泳", met: 10.3 },
  { name: "自由式游泳", met: 8.3 },
  { name: "仰式游泳", met: 7.0 },
  { name: "水中有氧", met: 5.5 },
  { name: "單車休閒騎", met: 4.0 },
  { name: "單車中等速度", met: 6.8 },
  { name: "飛輪", met: 8.5 },
  { name: "室內腳踏車", met: 6.0 },
  { name: "重量訓練（一般）", met: 5.0 },
  { name: "重量訓練（高強度）", met: 6.0 },
  { name: "徒手訓練", met: 6.0 },
  { name: "HIIT 高強度間歇", met: 9.0 },
  { name: "瑜伽", met: 2.5 },
  { name: "皮拉提斯", met: 3.0 },
  { name: "伸展", met: 2.3 },
  { name: "跳繩", met: 11.8 },
  { name: "籃球", met: 8.0 },
  { name: "羽球", met: 7.0 },
  { name: "桌球", met: 4.0 },
  { name: "網球", met: 7.3 },
  { name: "足球", met: 10.0 },
  { name: "舞蹈", met: 5.0 },
  { name: "有氧舞蹈", met: 7.3 },
  { name: "拳擊訓練", met: 7.8 },
  { name: "划船機", met: 7.0 },
  { name: "橢圓機", met: 5.0 },
  { name: "打掃家務", met: 3.3 },
  { name: "搬運重物", met: 6.0 },
];

export const ENCOURAGEMENTS = [
  "不用每一餐都完美，持續記錄就已經在進步。",
  "今天的小選擇，會慢慢變成你想要的樣子。",
  "體重只是數字，能穩定照顧自己才是真本事。",
  "有吃飽、有運動、有休息，才走得長久。",
  "偶爾超過沒關係，下一餐回到節奏就好。",
  "你不需要贏過昨天，只要沒有放棄今天。",
  "記下一餐不是限制自己，是多理解自己一點。",
  "慢慢來比較快，穩定比極端更有力量。",
];
